#! /usr/bin/env python
# RocketUI client library


def options(opt):
    return


def configure(conf):
    return


def build(bld):
    source = [
        "rocketuiimpl.cpp",
        "rocketsystem.cpp",
        "rocketfilesystem.cpp",
        "rocketrender_d3d9.cpp",
    ]

    includes = [
        ".",
        "../public",
        "../public/rocketui",
    ]

    libs = [
        "tier0",
        "tier1",
        "tier2",
        "tier3",
        "vstdlib",
        "interfaces",
        "bitmap",
        "vtf",
        "mathlib",
        "rmlui",
        "RmlCore",
        "RmlDebugger",
    ]

    bld.shlib(
        source=source,
        target="rocketui_client",
        features="cxx",
        includes=includes,
        use=libs + ["SDL3", "FREETYPE", "FONTCONFIG"],
        lib=[],
        install_path=bld.env.BINPATH,
        subsystem=bld.env.MSVC_SUBSYSTEM,
        idx=bld.get_taskgen_count(),
    )
