//========= Copyright (c) 1996-2005, Valve Corporation, All rights reserved. ============//
//
// Purpose: 
//
//=============================================================================//

#ifndef MAPINFO_H
#define MAPINFO_H

#include "reflect_annotations.h"


#include "baseentity.h"


class CMapInfo : public CPointEntity
{
public :

	DECLARE_DATADESC();
	DECLARE_CLASS( CMapInfo, CPointEntity );
	
	CMapInfo();
	virtual ~CMapInfo();

	bool KeyValue( const char *szKeyName, const char *szValue );
	void Spawn();

	[[= ks::reflect::Input{ .name = "FireWinCondition", .type = FIELD_INTEGER } ]] void InputFireWinCondition( inputdata_t &inputdata );

public:
	int m_iBuyingStatus;
	float m_flBombRadius;
	[[= ks::reflect::Key{ .name = "petpopulation" } ]] int m_iPetPopulation;
	[[= ks::reflect::Key{ .name = "usenormalspawnsfordm" } ]] bool m_bUseNormalSpawnsForDM;
	[[= ks::reflect::Key{ .name = "disableautogenerateddmspawns" } ]] bool m_bDisableAutoGeneratedDMSpawns;
	[[= ks::reflect::Key{ .name = "botmaxvisiondistance" } ]] float m_flBotMaxVisionDistance;
	[[= ks::reflect::Key{ .name = "hostagecount" } ]] int m_iHostageCount;
};


// The info_map_parameters entity in this map (only one is allowed for).
extern CMapInfo *g_pMapInfo;


#endif // MAPINFO_H
