#! /usr/bin/env python


def options(opt):
    return


def configure(conf):
    conf.define("NO_STRING_T", True)


def build(bld):
    libs = [
        "tier0",
        "memoverride",
        "public_common",
        "tier1",
        "tier2",
        "interfaces",
        "vstdlib",
        "mathlib",
        "SDL3",
    ]

    includes = []

    source = [
        "inputstacksystem.cpp",
        "inputsystem.cpp",
        "steamcontroller.cpp",
        "key_translation.cpp",
    ]

    source += ["joystick_linux.cpp"]

    bld.objects(
        source=source,
        target="inputsystem",
        features="cxx",
        includes=includes,
        use=libs,
        idx=bld.get_taskgen_count(),
    )
