#! /usr/bin/env python


def options(opt):
    return


def configure(conf):
    conf.define("FILESYSTEM_STDIO_EXPORTS", True)


def build(bld):
    libs = ["tier0", "memoverride", "tier1", "tier2", "interfaces", "vstdlib", "vpk"]

    includes = []

    source = [
        "basefilesystem.cpp",
        "basefilesystemasync.cpp",
        "filetracker.cpp",
        "filesystemasync.cpp",
        "filesystem_stdio.cpp",
        "../public/kevvaluescompiler.cpp",
        "../public/zip_utils.cpp",
    ]

    source += ["linux_support.cpp"]

    bld.objects(
        source=source,
        target="filesystem_stdio",
        features="cxx",
        includes=includes,
        use=libs,
        idx=bld.get_taskgen_count(),
    )
