#! /usr/bin/env python


def options(opt):
    return


def configure(conf):
    conf.define("MDLCACHE_DLL_EXPORT", True)


def build(bld):
    libs = [
        "tier0",
        "memoverride",
        "tier1",
        "tier2",
        "tier3",
        "interfaces",
        "vstdlib",
        "mathlib",
    ]

    includes = []

    source = [
        "datacache.cpp",
        "mdlcache.cpp",
        "mdlcombine.cpp",
        "vtfcombine.cpp",
        "resourceaccesscontrol.cpp",
        "precachesystem.cpp",
        "../public/studio_virtualmodel.cpp",
        "../common/studiobyteswap.cpp",
        "../utils/common/datalinker.cpp",
    ]

    bld.objects(
        source=source,
        target="datacache",
        features="cxx",
        includes=includes,
        use=libs,
        idx=bld.get_taskgen_count(),
    )
