#! /usr/bin/env python


def options(opt):
    return


def configure(conf):
    conf.define("LAUNCHERONLY", True)


def build(bld):
    libs = [
        "tier0",
        "memoverride",
        "appframework",
        "tier1",
        "tier2",
        "tier3",
        "interfaces",
        "vstdlib",
        "togl",
        "SDL3",
    ]

    includes = []

    source = [
        "../public/filesystem_init.cpp",
        "launcher.cpp",
        "reslistgenerator.cpp",
    ]

    bld.shlib(
        source=source,
        target="launcher",
        features="cxx",
        includes=includes,
        use=libs,
        install_path=bld.env.BINPATH,
        subsystem=bld.env.MSVC_SUBSYSTEM,
        idx=bld.get_taskgen_count(),
    )
