#! /usr/bin/env python


def options(opt):
    return


def configure(conf):
    conf.define("SOUNDEMITTERSYSTEM_EXPORTS", True)


def build(bld):
    libs = [
        "tier0",
        "memoverride",
        "public_common",
        "tier1",
        "tier2",
        "tier3",
        "interfaces",
        "vstdlib",
    ]

    includes = ["."]

    source = [
        "soundemittersystembase.cpp",
        "../public/SoundParametersInternal.cpp",
    ]

    bld.objects(
        source=source,
        target="soundemittersystem",
        features="cxx",
        includes=includes,
        use=libs,
        idx=bld.get_taskgen_count(),
    )
