#! /usr/bin/env python


def options(opt):
    return


def configure(conf):
    return


def build(bld):
    libs = [
        "tier0",
        "memoverride",
        "tier1",
        "tier2",
        "tier3",
        "interfaces",
        "appframework",
        "vstdlib",
        "mathlib",
    ]

    includes = ["."]

    source = [
        "console/textconsole.cpp",
        "console/TextConsoleUnix.cpp",
        "sys_common.cpp",
        "sys_ded.cpp",
        "sys_linux.cpp",
        "sys_subproc.cpp",
    ]

    bld.objects(
        source=source,
        target="dedicated",
        features="cxx",
        includes=includes,
        use=libs,
        idx=bld.get_taskgen_count(),
    )
