#! /usr/bin/env python


def options(opt):
    return


def configure(conf):
    return


def build(bld):
    libs = []

    includes = []

    source = [
        "AppSystemGroup.cpp",
        "../public/filesystem_init.cpp",
    ]

    source += ["posixapp.cpp", "sdlmgr.cpp"]

    bld.stlib(
        source=source,
        target="appframework",
        features="cxx",
        includes=includes,
        use=libs,
        subsystem=bld.env.MSVC_SUBSYSTEM,
        idx=bld.get_taskgen_count(),
    )
