#! /usr/bin/env python


def options(opt):
    return


def configure(conf):
    return


def build(bld):
    libs = []

    includes = []

    source = ["d3dxmath.cpp"]

    bld.stlib(
        source=source,
        target="d3dx",
        features="c",
        includes=includes,
        use=libs,
        subsystem=bld.env.MSVC_SUBSYSTEM,
        idx=bld.get_taskgen_count(),
    )
