#! /usr/bin/env python


def options(opt):
    return


def configure(conf):
    return


def build(bld):
    libs = [
        "tier0",
        "memoverride",
        "public_common",
        "tier1",
        "tier2",
        "interfaces",
        "vstdlib",
    ]

    includes = []

    source = [
        "localize.cpp",
        "../public/UnicodeFileHelpers.cpp",
    ]

    bld.objects(
        source=source,
        target="localize",
        features="cxx",
        includes=includes,
        use=libs,
        idx=bld.get_taskgen_count(),
    )
