#! /usr/bin/env python


def options(opt):
    return


def configure(conf):
    conf.define("VSTDLIB_DLL_EXPORT", True)


def build(bld):
    libs = ["tier0", "memoverride", "tier1", "interfaces"]

    includes = []

    source = [
        "coroutine.cpp",
        "cvar.cpp",
        "jobthread.cpp",
        "keyvaluessystem.cpp",
        "random.cpp",
        "vcover.cpp",
        "eventsystem.cpp",
        "vstrtools.cpp",
        "vstdlib_strtools.cpp",
    ]

    if bld.env.DEST_OS == "win32":
        source += ["processutils.cpp"]
        if bld.env.ALLOW64:
            source += ["getstackptr64.masm"]

    bld.objects(
        source=source,
        target="vstdlib",
        features="cxx",
        includes=includes,
        use=libs,
        idx=bld.get_taskgen_count(),
    )
