#! /usr/bin/env python


def options(opt):
    return


def configure(conf):
    conf.define("MATCHMAKING_DLL", True)
    conf.define("NO_STRING_T", True)
    conf.define("VECTOR", True)
    conf.define("NO_STEAM_GAMECOORDINATOR", True)


def build(bld):
    libs = [
        "tier0",
        "memoverride",
        "public_common",
        "matchmaking_base",
        "tier1",
        "tier2",
        "tier3",
        "interfaces",
        "vstdlib",
        "mathlib",
        "generated_proto",
        "protobuf",
    ]

    includes = [
        "../common/xlast_csgo",
        "../game/shared",
        "../thirdparty/protobuf-2.6.1/src",
    ]

    source = [
        "cstrike15/mm_title.cpp",
        "cstrike15/mm_title_gamesettingsmgr.cpp",
        "cstrike15/mm_title_main.cpp",
        "cstrike15/mm_title_richpresence.cpp",
        "cstrike15/mm_title_titledata.cpp",
        "../game/shared/cstrike15/gametypes.cpp",
    ]

    source_matchmaking_base = [
        "matchmakingqos.cpp",
        "mm_events.cpp",
        "mm_extensions.cpp",
        "mm_framework.cpp",
        "mm_netmsgcontroller.cpp",
        "mm_session.cpp",
        "mm_voice.cpp",
        "mm_netmgr.cpp",
        "mm_session_offline_custom.cpp",
        "sys_session.cpp",
        "steam_apihook.cpp",
        "matchsystem.cpp",
        "player.cpp",
        "playermanager.cpp",
        "extkeyvalues.cpp",
        "main.cpp",
    ]

    for target in ("matchmaking", "matchmaking_ds"):
        bld.shlib(
            source=source,
            target=target,
            features="cxx",
            includes=includes,
            use=libs,
            install_path=bld.env.GAMEBIN,
            subsystem=bld.env.MSVC_SUBSYSTEM,
            idx=bld.get_taskgen_count(),
        )

    bld.stlib(
        source=source_matchmaking_base,
        target="matchmaking_base",
        features="cxx",
        includes=includes,
        subsystem=bld.env.MSVC_SUBSYSTEM,
        idx=bld.get_taskgen_count(),
    )
